import { db } from '@/db';
import { districts } from '@/db/schema';

async function main() {
    const sampleDistricts = [
        // Jammu and Kashmir (01)
        { districtCode: '0101', districtNameEn: 'Anantnag', districtNameHi: 'अनंतनाग', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0102', districtNameEn: 'Bandipora', districtNameHi: 'बांदीपोरा', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0103', districtNameEn: 'Baramulla', districtNameHi: 'बारामूला', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0104', districtNameEn: 'Budgam', districtNameHi: 'बडगाम', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0105', districtNameEn: 'Doda', districtNameHi: 'डोडा', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0106', districtNameEn: 'Ganderbal', districtNameHi: 'गांदरबल', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0107', districtNameEn: 'Jammu', districtNameHi: 'जम्मू', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0108', districtNameEn: 'Kathua', districtNameHi: 'कठुआ', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0109', districtNameEn: 'Kishtwar', districtNameHi: 'किश्तवाड़', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0110', districtNameEn: 'Kulgam', districtNameHi: 'कुलगाम', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0111', districtNameEn: 'Kupwara', districtNameHi: 'कुपवाड़ा', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0112', districtNameEn: 'Poonch', districtNameHi: 'पुंछ', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0113', districtNameEn: 'Pulwama', districtNameHi: 'पुलवामा', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0114', districtNameEn: 'Rajouri', districtNameHi: 'राजौरी', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0115', districtNameEn: 'Ramban', districtNameHi: 'रामबन', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0116', districtNameEn: 'Reasi', districtNameHi: 'रियासी', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0117', districtNameEn: 'Samba', districtNameHi: 'सांबा', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0118', districtNameEn: 'Shopian', districtNameHi: 'शोपियां', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0119', districtNameEn: 'Srinagar', districtNameHi: 'श्रीनगर', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0120', districtNameEn: 'Udhampur', districtNameHi: 'उधमपुर', stateName: 'Jammu and Kashmir', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },

        // Himachal Pradesh (02)
        { districtCode: '0201', districtNameEn: 'Bilaspur', districtNameHi: 'बिलासपुर', stateName: 'Himachal Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0202', districtNameEn: 'Chamba', districtNameHi: 'चंबा', stateName: 'Himachal Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0203', districtNameEn: 'Hamirpur', districtNameHi: 'हमीरपुर', stateName: 'Himachal Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0204', districtNameEn: 'Kangra', districtNameHi: 'कांगड़ा', stateName: 'Himachal Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0205', districtNameEn: 'Kinnaur', districtNameHi: 'किन्नौर', stateName: 'Himachal Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0206', districtNameEn: 'Kullu', districtNameHi: 'कुल्लू', stateName: 'Himachal Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0207', districtNameEn: 'Lahaul and Spiti', districtNameHi: 'लाहौल और स्पीति', stateName: 'Himachal Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0208', districtNameEn: 'Mandi', districtNameHi: 'मंडी', stateName: 'Himachal Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0209', districtNameEn: 'Shimla', districtNameHi: 'शिमला', stateName: 'Himachal Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0210', districtNameEn: 'Sirmaur', districtNameHi: 'सिरमौर', stateName: 'Himachal Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0211', districtNameEn: 'Solan', districtNameHi: 'सोलन', stateName: 'Himachal Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0212', districtNameEn: 'Una', districtNameHi: 'ऊना', stateName: 'Himachal Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },

        // Punjab (03)
        { districtCode: '0301', districtNameEn: 'Amritsar', districtNameHi: 'अमृतसर', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0302', districtNameEn: 'Barnala', districtNameHi: 'बरनाला', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0303', districtNameEn: 'Bathinda', districtNameHi: 'बठिंडा', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0304', districtNameEn: 'Faridkot', districtNameHi: 'फरीदकोट', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0305', districtNameEn: 'Fatehgarh Sahib', districtNameHi: 'फतेहगढ़ साहिब', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0306', districtNameEn: 'Fazilka', districtNameHi: 'फाजिल्का', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0307', districtNameEn: 'Ferozepur', districtNameHi: 'फिरोजपुर', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0308', districtNameEn: 'Gurdaspur', districtNameHi: 'गुरदासपुर', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0309', districtNameEn: 'Hoshiarpur', districtNameHi: 'होशियारपुर', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0310', districtNameEn: 'Jalandhar', districtNameHi: 'जालंधर', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0311', districtNameEn: 'Kapurthala', districtNameHi: 'कपूरथला', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0312', districtNameEn: 'Ludhiana', districtNameHi: 'लुधियाना', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0313', districtNameEn: 'Mansa', districtNameHi: 'मानसा', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0314', districtNameEn: 'Moga', districtNameHi: 'मोगा', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0315', districtNameEn: 'Muktsar', districtNameHi: 'मुक्तसर', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0316', districtNameEn: 'Pathankot', districtNameHi: 'पठानकोट', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0317', districtNameEn: 'Patiala', districtNameHi: 'पटियाला', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0318', districtNameEn: 'Rupnagar', districtNameHi: 'रूपनगर', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0319', districtNameEn: 'Sahibzada Ajit Singh Nagar', districtNameHi: 'साहिबजादा अजीत सिंह नगर', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0320', districtNameEn: 'Sangrur', districtNameHi: 'संगरूर', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0321', districtNameEn: 'Shahid Bhagat Singh Nagar', districtNameHi: 'शहीद भगत सिंह नगर', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0322', districtNameEn: 'Tarn Taran', districtNameHi: 'तरन तारन', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0323', districtNameEn: 'Malerkotla', districtNameHi: 'मलेरकोटला', stateName: 'Punjab', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },

        // Chandigarh (04)
        { districtCode: '0401', districtNameEn: 'Chandigarh', districtNameHi: 'चंडीगढ़', stateName: 'Chandigarh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },

        // Uttarakhand (05)
        { districtCode: '0501', districtNameEn: 'Almora', districtNameHi: 'अल्मोड़ा', stateName: 'Uttarakhand', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0502', districtNameEn: 'Bageshwar', districtNameHi: 'बागेश्वर', stateName: 'Uttarakhand', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0503', districtNameEn: 'Chamoli', districtNameHi: 'चमोली', stateName: 'Uttarakhand', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0504', districtNameEn: 'Champawat', districtNameHi: 'चंपावत', stateName: 'Uttarakhand', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0505', districtNameEn: 'Dehradun', districtNameHi: 'देहरादून', stateName: 'Uttarakhand', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0506', districtNameEn: 'Haridwar', districtNameHi: 'हरिद्वार', stateName: 'Uttarakhand', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0507', districtNameEn: 'Nainital', districtNameHi: 'नैनीताल', stateName: 'Uttarakhand', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0508', districtNameEn: 'Pauri Garhwal', districtNameHi: 'पौड़ी गढ़वाल', stateName: 'Uttarakhand', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0509', districtNameEn: 'Pithoragarh', districtNameHi: 'पिथौरागढ़', stateName: 'Uttarakhand', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0510', districtNameEn: 'Rudraprayag', districtNameHi: 'रुद्रप्रयाग', stateName: 'Uttarakhand', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0511', districtNameEn: 'Tehri Garhwal', districtNameHi: 'टिहरी गढ़वाल', stateName: 'Uttarakhand', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0512', districtNameEn: 'Udham Singh Nagar', districtNameHi: 'उधम सिंह नगर', stateName: 'Uttarakhand', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0513', districtNameEn: 'Uttarkashi', districtNameHi: 'उत्तरकाशी', stateName: 'Uttarakhand', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },

        // Haryana (06)
        { districtCode: '0601', districtNameEn: 'Ambala', districtNameHi: 'अंबाला', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0602', districtNameEn: 'Bhiwani', districtNameHi: 'भिवानी', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0603', districtNameEn: 'Charkhi Dadri', districtNameHi: 'चरखी दादरी', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0604', districtNameEn: 'Faridabad', districtNameHi: 'फरीदाबाद', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0605', districtNameEn: 'Fatehabad', districtNameHi: 'फतेहाबाद', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0606', districtNameEn: 'Gurugram', districtNameHi: 'गुरुग्राम', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0607', districtNameEn: 'Hisar', districtNameHi: 'हिसार', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0608', districtNameEn: 'Jhajjar', districtNameHi: 'झज्जर', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0609', districtNameEn: 'Jind', districtNameHi: 'जींद', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0610', districtNameEn: 'Kaithal', districtNameHi: 'कैथल', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0611', districtNameEn: 'Karnal', districtNameHi: 'करनाल', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0612', districtNameEn: 'Kurukshetra', districtNameHi: 'कुरुक्षेत्र', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0613', districtNameEn: 'Mahendragarh', districtNameHi: 'महेंद्रगढ़', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0614', districtNameEn: 'Nuh', districtNameHi: 'नूंह', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0615', districtNameEn: 'Palwal', districtNameHi: 'पलवल', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0616', districtNameEn: 'Panchkula', districtNameHi: 'पंचकुला', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0617', districtNameEn: 'Panipat', districtNameHi: 'पानीपत', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0618', districtNameEn: 'Rewari', districtNameHi: 'रेवाड़ी', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0619', districtNameEn: 'Rohtak', districtNameHi: 'रोहतक', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0620', districtNameEn: 'Sirsa', districtNameHi: 'सिरसा', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0621', districtNameEn: 'Sonipat', districtNameHi: 'सोनीपत', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0622', districtNameEn: 'Yamunanagar', districtNameHi: 'यमुनानगर', stateName: 'Haryana', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },

        // Delhi (07)
        { districtCode: '0701', districtNameEn: 'Central Delhi', districtNameHi: 'मध्य दिल्ली', stateName: 'Delhi', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0702', districtNameEn: 'East Delhi', districtNameHi: 'पूर्वी दिल्ली', stateName: 'Delhi', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0703', districtNameEn: 'New Delhi', districtNameHi: 'नई दिल्ली', stateName: 'Delhi', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0704', districtNameEn: 'North Delhi', districtNameHi: 'उत्तर दिल्ली', stateName: 'Delhi', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0705', districtNameEn: 'North East Delhi', districtNameHi: 'उत्तर पूर्वी दिल्ली', stateName: 'Delhi', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0706', districtNameEn: 'North West Delhi', districtNameHi: 'उत्तर पश्चिमी दिल्ली', stateName: 'Delhi', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0707', districtNameEn: 'Shahdara', districtNameHi: 'शाहदरा', stateName: 'Delhi', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0708', districtNameEn: 'South Delhi', districtNameHi: 'दक्षिण दिल्ली', stateName: 'Delhi', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0709', districtNameEn: 'South East Delhi', districtNameHi: 'दक्षिण पूर्वी दिल्ली', stateName: 'Delhi', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0710', districtNameEn: 'South West Delhi', districtNameHi: 'दक्षिण पश्चिमी दिल्ली', stateName: 'Delhi', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0711', districtNameEn: 'West Delhi', districtNameHi: 'पश्चिमी दिल्ली', stateName: 'Delhi', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },

        // Rajasthan (08)
        { districtCode: '0801', districtNameEn: 'Ajmer', districtNameHi: 'अजमेर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0802', districtNameEn: 'Alwar', districtNameHi: 'अलवर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0803', districtNameEn: 'Banswara', districtNameHi: 'बांसवाड़ा', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0804', districtNameEn: 'Baran', districtNameHi: 'बारां', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0805', districtNameEn: 'Barmer', districtNameHi: 'बाड़मेर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0806', districtNameEn: 'Bharatpur', districtNameHi: 'भरतपुर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0807', districtNameEn: 'Bhilwara', districtNameHi: 'भीलवाड़ा', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0808', districtNameEn: 'Bikaner', districtNameHi: 'बीकानेर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0809', districtNameEn: 'Bundi', districtNameHi: 'बूंदी', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0810', districtNameEn: 'Chittorgarh', districtNameHi: 'चित्तौड़गढ़', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0811', districtNameEn: 'Churu', districtNameHi: 'चूरू', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0812', districtNameEn: 'Dausa', districtNameHi: 'दौसा', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0813', districtNameEn: 'Dholpur', districtNameHi: 'धौलपुर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0814', districtNameEn: 'Dungarpur', districtNameHi: 'डूंगरपुर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0815', districtNameEn: 'Hanumangarh', districtNameHi: 'हनुमानगढ़', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0816', districtNameEn: 'Jaipur', districtNameHi: 'जयपुर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0817', districtNameEn: 'Jaisalmer', districtNameHi: 'जैसलमेर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0818', districtNameEn: 'Jalore', districtNameHi: 'जालोर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0819', districtNameEn: 'Jhalawar', districtNameHi: 'झालावाड़', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0820', districtNameEn: 'Jhunjhunu', districtNameHi: 'झुंझुनू', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0821', districtNameEn: 'Jodhpur', districtNameHi: 'जोधपुर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0822', districtNameEn: 'Karauli', districtNameHi: 'करौली', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0823', districtNameEn: 'Kota', districtNameHi: 'कोटा', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0824', districtNameEn: 'Nagaur', districtNameHi: 'नागौर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0825', districtNameEn: 'Pali', districtNameHi: 'पाली', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0826', districtNameEn: 'Pratapgarh', districtNameHi: 'प्रतापगढ़', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0827', districtNameEn: 'Rajsamand', districtNameHi: 'राजसमंद', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0828', districtNameEn: 'Sawai Madhopur', districtNameHi: 'सवाई माधोपुर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0829', districtNameEn: 'Sikar', districtNameHi: 'सीकर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0830', districtNameEn: 'Sirohi', districtNameHi: 'सिरोही', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0831', districtNameEn: 'Sri Ganganagar', districtNameHi: 'श्री गंगानगर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0832', districtNameEn: 'Tonk', districtNameHi: 'टोंक', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0833', districtNameEn: 'Udaipur', districtNameHi: 'उदयपुर', stateName: 'Rajasthan', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },

        // Uttar Pradesh (09) - First 20 districts
        { districtCode: '0901', districtNameEn: 'Agra', districtNameHi: 'आगरा', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0902', districtNameEn: 'Aligarh', districtNameHi: 'अलीगढ़', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0903', districtNameEn: 'Ambedkar Nagar', districtNameHi: 'अम्बेडकर नगर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0904', districtNameEn: 'Amethi', districtNameHi: 'अमेठी', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0905', districtNameEn: 'Amroha', districtNameHi: 'अमरोहा', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0906', districtNameEn: 'Auraiya', districtNameHi: 'औरैया', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0907', districtNameEn: 'Ayodhya', districtNameHi: 'अयोध्या', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0908', districtNameEn: 'Azamgarh', districtNameHi: 'आजमगढ़', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0909', districtNameEn: 'Baghpat', districtNameHi: 'बागपत', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0910', districtNameEn: 'Bahraich', districtNameHi: 'बहराइच', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0911', districtNameEn: 'Ballia', districtNameHi: 'बलिया', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0912', districtNameEn: 'Balrampur', districtNameHi: 'बलरामपुर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0913', districtNameEn: 'Banda', districtNameHi: 'बांदा', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0914', districtNameEn: 'Barabanki', districtNameHi: 'बाराबंकी', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0915', districtNameEn: 'Bareilly', districtNameHi: 'बरेली', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0916', districtNameEn: 'Basti', districtNameHi: 'बस्ती', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0917', districtNameEn: 'Bhadohi', districtNameHi: 'भदोही', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0918', districtNameEn: 'Bijnor', districtNameHi: 'बिजनौर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0919', districtNameEn: 'Budaun', districtNameHi: 'बदायूं', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0920', districtNameEn: 'Bulandshahr', districtNameHi: 'बुलंदशहर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0921', districtNameEn: 'Chandauli', districtNameHi: 'चंदौली', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0922', districtNameEn: 'Chitrakoot', districtNameHi: 'चित्रकूट', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0923', districtNameEn: 'Deoria', districtNameHi: 'देवरिया', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0924', districtNameEn: 'Etah', districtNameHi: 'एटा', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0925', districtNameEn: 'Etawah', districtNameHi: 'इटावा', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0926', districtNameEn: 'Farrukhabad', districtNameHi: 'फर्रुखाबाद', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0927', districtNameEn: 'Fatehpur', districtNameHi: 'फतेहपुर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0928', districtNameEn: 'Firozabad', districtNameHi: 'फिरोजाबाद', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0929', districtNameEn: 'Gautam Buddha Nagar', districtNameHi: 'गौतम बुद्ध नगर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0930', districtNameEn: 'Ghaziabad', districtNameHi: 'गाजियाबाद', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0931', districtNameEn: 'Ghazipur', districtNameHi: 'गाजीपुर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0932', districtNameEn: 'Gonda', districtNameHi: 'गोंडा', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0933', districtNameEn: 'Gorakhpur', districtNameHi: 'गोरखपुर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0934', districtNameEn: 'Hamirpur', districtNameHi: 'हमीरपुर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0935', districtNameEn: 'Hapur', districtNameHi: 'हापुड़', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0936', districtNameEn: 'Hardoi', districtNameHi: 'हरदोई', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0937', districtNameEn: 'Hathras', districtNameHi: 'हाथरस', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0938', districtNameEn: 'Jalaun', districtNameHi: 'जालौन', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0939', districtNameEn: 'Jaunpur', districtNameHi: 'जौनपुर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0940', districtNameEn: 'Jhansi', districtNameHi: 'झांसी', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0941', districtNameEn: 'Kannauj', districtNameHi: 'कन्नौज', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0942', districtNameEn: 'Kanpur Dehat', districtNameHi: 'कानपुर देहात', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0943', districtNameEn: 'Kanpur Nagar', districtNameHi: 'कानपुर नगर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0944', districtNameEn: 'Kasganj', districtNameHi: 'कासगंज', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0945', districtNameEn: 'Kaushambi', districtNameHi: 'कौशाम्बी', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0946', districtNameEn: 'Kushinagar', districtNameHi: 'कुशीनगर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0947', districtNameEn: 'Lakhimpur Kheri', districtNameHi: 'लखीमपुर खीरी', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0948', districtNameEn: 'Lalitpur', districtNameHi: 'ललितपुर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0949', districtNameEn: 'Lucknow', districtNameHi: 'लखनऊ', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0950', districtNameEn: 'Maharajganj', districtNameHi: 'महाराजगंज', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0951', districtNameEn: 'Mahoba', districtNameHi: 'महोबा', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0952', districtNameEn: 'Mainpuri', districtNameHi: 'मैनपुरी', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0953', districtNameEn: 'Mathura', districtNameHi: 'मथुरा', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0954', districtNameEn: 'Mau', districtNameHi: 'मऊ', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0955', districtNameEn: 'Meerut', districtNameHi: 'मेरठ', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0956', districtNameEn: 'Mirzapur', districtNameHi: 'मिर्जापुर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0957', districtNameEn: 'Moradabad', districtNameHi: 'मुरादाबाद', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0958', districtNameEn: 'Muzaffarnagar', districtNameHi: 'मुजफ्फरनगर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0959', districtNameEn: 'Pilibhit', districtNameHi: 'पीलीभीत', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0960', districtNameEn: 'Pratapgarh', districtNameHi: 'प्रतापगढ़', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0961', districtNameEn: 'Prayagraj', districtNameHi: 'प्रयागराज', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0962', districtNameEn: 'Raebareli', districtNameHi: 'रायबरेली', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0963', districtNameEn: 'Rampur', districtNameHi: 'रामपुर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0964', districtNameEn: 'Saharanpur', districtNameHi: 'सहारनपुर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0965', districtNameEn: 'Sambhal', districtNameHi: 'संभल', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0966', districtNameEn: 'Sant Kabir Nagar', districtNameHi: 'संत कबीर नगर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0967', districtNameEn: 'Shahjahanpur', districtNameHi: 'शाहजहांपुर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0968', districtNameEn: 'Shamli', districtNameHi: 'शामली', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0969', districtNameEn: 'Shravasti', districtNameHi: 'श्रावस्ती', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0970', districtNameEn: 'Siddharthnagar', districtNameHi: 'सिद्धार्थनगर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0971', districtNameEn: 'Sitapur', districtNameHi: 'सीतापुर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0972', districtNameEn: 'Sonbhadra', districtNameHi: 'सोनभद्र', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0973', districtNameEn: 'Sultanpur', districtNameHi: 'सुल्तानपुर', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0974', districtNameEn: 'Unnao', districtNameHi: 'उन्नाव', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '0975', districtNameEn: 'Varanasi', districtNameHi: 'वाराणसी', stateName: 'Uttar Pradesh', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },

        // Bihar (10)
        { districtCode: '1001', districtNameEn: 'Araria', districtNameHi: 'अररिया', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1002', districtNameEn: 'Arwal', districtNameHi: 'अरवल', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1003', districtNameEn: 'Aurangabad', districtNameHi: 'औरंगाबाद', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1004', districtNameEn: 'Banka', districtNameHi: 'बांका', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1005', districtNameEn: 'Begusarai', districtNameHi: 'बेगूसराय', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1006', districtNameEn: 'Bhagalpur', districtNameHi: 'भागलपुर', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1007', districtNameEn: 'Bhojpur', districtNameHi: 'भोजपुर', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1008', districtNameEn: 'Buxar', districtNameHi: 'बक्सर', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1009', districtNameEn: 'Darbhanga', districtNameHi: 'दरभंगा', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1010', districtNameEn: 'East Champaran', districtNameHi: 'पूर्वी चंपारण', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1011', districtNameEn: 'Gaya', districtNameHi: 'गया', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1012', districtNameEn: 'Gopalganj', districtNameHi: 'गोपालगंज', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1013', districtNameEn: 'Jamui', districtNameHi: 'जमुई', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1014', districtNameEn: 'Jehanabad', districtNameHi: 'जहानाबाद', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1015', districtNameEn: 'Kaimur', districtNameHi: 'कैमूर', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1016', districtNameEn: 'Katihar', districtNameHi: 'कटिहार', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1017', districtNameEn: 'Khagaria', districtNameHi: 'खगड़िया', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1018', districtNameEn: 'Kishanganj', districtNameHi: 'किशनगंज', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1019', districtNameEn: 'Lakhisarai', districtNameHi: 'लखीसराय', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1020', districtNameEn: 'Madhepura', districtNameHi: 'मधेपुरा', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1021', districtNameEn: 'Madhubani', districtNameHi: 'मधुबनी', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1022', districtNameEn: 'Munger', districtNameHi: 'मुंगेर', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1023', districtNameEn: 'Muzaffarpur', districtNameHi: 'मुजफ्फरपुर', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1024', districtNameEn: 'Nalanda', districtNameHi: 'नालंदा', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1025', districtNameEn: 'Nawada', districtNameHi: 'नवादा', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1026', districtNameEn: 'Patna', districtNameHi: 'पटना', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1027', districtNameEn: 'Purnia', districtNameHi: 'पूर्णिया', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1028', districtNameEn: 'Rohtas', districtNameHi: 'रोहतास', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1029', districtNameEn: 'Saharsa', districtNameHi: 'सहरसा', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1030', districtNameEn: 'Samastipur', districtNameHi: 'समस्तीपुर', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1031', districtNameEn: 'Saran', districtNameHi: 'सारण', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1032', districtNameEn: 'Sheikhpura', districtNameHi: 'शेखपुरा', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1033', districtNameEn: 'Sheohar', districtNameHi: 'शिवहर', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1034', districtNameEn: 'Sitamarhi', districtNameHi: 'सीतामढ़ी', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1035', districtNameEn: 'Siwan', districtNameHi: 'सिवान', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1036', districtNameEn: 'Supaul', districtNameHi: 'सुपौल', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1037', districtNameEn: 'Vaishali', districtNameHi: 'वैशाली', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() },
        { districtCode: '1038', districtNameEn: 'West Champaran', districtNameHi: 'पश्चिमी चंपारण', stateName: 'Bihar', createdAt: new Date('2024-01-01').toISOString(), updatedAt: new Date('2024-01-01').toISOString() }
    ];

    await db.insert(districts).values(sampleDistricts);
    
    console.log('✅ Districts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});